version: "3"
services:
    main_app:
        build: .
        command: python src/main.python
        links:
            - db
    
    db:
        image: postgres
        container_name: "db_queens"
        environment: 
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DATABASE=queens
        ports: 
            - "54320:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data